name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate static sites
        run: |
          echo "Building sites..."
          # Build from content files when present
          if ls .agent-content/*-content.json >/dev/null 2>&1; then
            for content in .agent-content/*-content.json; do
              name=$(basename "$content" -content.json)
              echo "Building $name from $content"
              node scripts/build-site.js --template="$name" --content="$content" || true
            done
          fi

          # Also build any template directories that contain an index.html
          for dir in 01-* 02-* 03-* 04-* 05-* flowai-saas nexus-ai-agency impact-nonprofit launchpad-startup luxe-ecommerce generated-site; do
            if [ -d "$dir" ] && [ -f "$dir/index.html" ]; then
              name=$(basename "$dir")
              echo "Building fallback for $name (no content JSON)"
              node scripts/build-site.js --template="$name" || true
            fi
          done
          # Ensure generated-site exists
          mkdir -p generated-site

      - name: Generate landing index
        run: |
          set -e
          out="generated-site/index.html"
          echo "Generating landing page at $out"
          cat > "$out" <<'HTML_HEADER'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Battle of the Bots — Series</title>
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
            <style>
              body{font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;background:#0b0f14;color:#e6edf3}
              header{padding:32px 20px;text-align:center}
              h1{margin:0;font-size:28px}
              p.lead{margin:8px 0 0;color:#9fb1c1}
              .grid{display:grid;gap:16px;padding:24px;grid-template-columns:repeat(auto-fill,minmax(260px,1fr))}
              .card{background:#121923;border:1px solid #1f2a37;border-radius:12px;padding:16px;transition:transform .1s ease, border-color .1s ease}
              .card:hover{transform:translateY(-2px);border-color:#2b3a4a}
              .name{font-weight:600;margin:0 0 8px}
              .desc{margin:0 0 12px;color:#9fb1c1;font-size:14px}
              .actions{display:flex;gap:10px}
              .btn{display:inline-block;background:#1f6feb;color:#fff;text-decoration:none;padding:8px 12px;border-radius:8px;font-weight:600}
              .btn.secondary{background:#2b3a4a}
              footer{padding:24px;text-align:center;color:#93a4b5}
            </style>
          </head>
          <body>
            <header>
              <h1>Battle of the Bots — Series</h1>
              <p class="lead">Five CLI agents, 30 minutes each, building sites “backwards”. Browse the demos below.</p>
            </header>
            <div class="grid">
          HTML_HEADER

          # Append one card per built subdirectory of generated-site
          for d in generated-site/*/ ; do
            name=$(basename "$d")
            if [ "$name" = "assets" ] || [ "$name" = "_next" ]; then continue; fi
            cat >> "$out" <<HTML_CARD
              <div class="card">
                <h3 class="name">$name</h3>
                <p class="desc">Live demo built by an agent during the challenge.</p>
                <div class="actions">
                  <a class="btn" href="./$name/" target="_blank" rel="noopener">View Demo</a>
                </div>
              </div>
          HTML_CARD
          done

          # Close the document
          cat >> "$out" <<'HTML_FOOTER'
            </div>
            <footer>Deployed via GitHub Pages</footer>
          </body>
          </html>
          HTML_FOOTER

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: generated-site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


